# TCL File Generated by Component Editor 21.1
# Sat Apr 02 01:43:05 EDT 2022
# DO NOT MODIFY


# 
# axi_seg "axi_seg" v1.0
#  2022.04.02.01:43:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi_seg
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_seg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi_seg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false

set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "axi_seg"
set_module_assignment embeddedsw.dts.group "axi_slave"


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hex_7seg_axil
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hex7seg.sv SYSTEM_VERILOG PATH ../../rtl/perf/hex7seg.sv
add_fileset_file hex_7seg_axil.sv SYSTEM_VERILOG PATH ../../rtl/perf/hex_7seg_axil.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 16
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 16
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter PIPELINE_OUTPUT INTEGER 0
set_parameter_property PIPELINE_OUTPUT DEFAULT_VALUE 0
set_parameter_property PIPELINE_OUTPUT DISPLAY_NAME PIPELINE_OUTPUT
set_parameter_property PIPELINE_OUTPUT TYPE INTEGER
set_parameter_property PIPELINE_OUTPUT ENABLED false
set_parameter_property PIPELINE_OUTPUT UNITS None
set_parameter_property PIPELINE_OUTPUT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock
set_interface_property altera_axi4lite_slave associatedReset reset_sink
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave s_axil_araddr araddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave s_axil_arprot arprot Input 3
add_interface_port altera_axi4lite_slave s_axil_arready arready Output 1
add_interface_port altera_axi4lite_slave s_axil_arvalid arvalid Input 1
add_interface_port altera_axi4lite_slave s_axil_awaddr awaddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave s_axil_awprot awprot Input 3
add_interface_port altera_axi4lite_slave s_axil_awready awready Output 1
add_interface_port altera_axi4lite_slave s_axil_awvalid awvalid Input 1
add_interface_port altera_axi4lite_slave s_axil_bready bready Input 1
add_interface_port altera_axi4lite_slave s_axil_bresp bresp Output 2
add_interface_port altera_axi4lite_slave s_axil_bvalid bvalid Output 1
add_interface_port altera_axi4lite_slave s_axil_rdata rdata Output "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave s_axil_rready rready Input 1
add_interface_port altera_axi4lite_slave s_axil_rresp rresp Output 2
add_interface_port altera_axi4lite_slave s_axil_rvalid rvalid Output 1
add_interface_port altera_axi4lite_slave s_axil_wdata wdata Input "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4lite_slave s_axil_wready wready Output 1
add_interface_port altera_axi4lite_slave s_axil_wstrb wstrb Input 4
add_interface_port altera_axi4lite_slave s_axil_wvalid wvalid Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end HEX0 hex0 Output 7
add_interface_port conduit_end HEX1 hex1 Output 7
add_interface_port conduit_end HEX2 hex2 Output 7
add_interface_port conduit_end HEX3 hex3 Output 7
add_interface_port conduit_end HEX4 hex4 Output 7
add_interface_port conduit_end HEX5 hex5 Output 7


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1

