# TCL File Generated by Component Editor 21.1
# Sat Apr 09 22:30:25 EDT 2022
# DO NOT MODIFY


# 
# axi_ram "axi ram" v1.0
#  2022.04.09.22:30:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi_ram
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_ram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "axi ram"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_ram
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file arbiter.v VERILOG PATH ../../rtl/verilog-axi/rtl/arbiter.v
add_fileset_file axi_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter.v
add_fileset_file axi_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter_rd.v
add_fileset_file axi_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter_wr.v
add_fileset_file axi_axil_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter.v
add_fileset_file axi_axil_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter_rd.v
add_fileset_file axi_axil_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter_wr.v
add_fileset_file axi_cdma.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_cdma.v
add_fileset_file axi_cdma_desc_mux.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_cdma_desc_mux.v
add_fileset_file axi_crossbar.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar.v
add_fileset_file axi_crossbar_addr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_addr.v
add_fileset_file axi_crossbar_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_rd.v
add_fileset_file axi_crossbar_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_wr.v
add_fileset_file axi_crossbar_wrap.py OTHER PATH ../../rtl/verilog-axi/rtl/axi_crossbar_wrap.py
add_fileset_file axi_dma.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma.v
add_fileset_file axi_dma_desc_mux.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_desc_mux.v
add_fileset_file axi_dma_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_rd.v
add_fileset_file axi_dma_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_wr.v
add_fileset_file axi_dp_ram.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dp_ram.v
add_fileset_file axi_fifo.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo.v
add_fileset_file axi_fifo_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo_rd.v
add_fileset_file axi_fifo_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo_wr.v
add_fileset_file axi_interconnect.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_interconnect.v
add_fileset_file axi_interconnect_wrap.py OTHER PATH ../../rtl/verilog-axi/rtl/axi_interconnect_wrap.py
add_fileset_file axi_ram.sv SYSTEM_VERILOG PATH ../../rtl/verilog-axi/rtl/axi_ram.sv TOP_LEVEL_FILE
add_fileset_file axi_ram_rd_if.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_ram_rd_if.v
add_fileset_file axi_ram_wr_if.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_ram_wr_if.v
add_fileset_file axi_ram_wr_rd_if.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_ram_wr_rd_if.v
add_fileset_file axi_register.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register.v
add_fileset_file axi_register_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register_rd.v
add_fileset_file axi_register_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register_wr.v
add_fileset_file axil_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter.v
add_fileset_file axil_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter_rd.v
add_fileset_file axil_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter_wr.v
add_fileset_file axil_cdc.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc.v
add_fileset_file axil_cdc_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc_rd.v
add_fileset_file axil_cdc_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc_wr.v
add_fileset_file axil_crossbar.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar.v
add_fileset_file axil_crossbar_addr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_addr.v
add_fileset_file axil_crossbar_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_rd.v
add_fileset_file axil_crossbar_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_wr.v
add_fileset_file axil_crossbar_wrap.py OTHER PATH ../../rtl/verilog-axi/rtl/axil_crossbar_wrap.py
add_fileset_file axil_dp_ram.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_dp_ram.v
add_fileset_file axil_interconnect.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_interconnect.v
add_fileset_file axil_interconnect_wrap.py OTHER PATH ../../rtl/verilog-axi/rtl/axil_interconnect_wrap.py
add_fileset_file axil_ram.sv SYSTEM_VERILOG PATH ../../rtl/verilog-axi/rtl/axil_ram.sv
add_fileset_file axil_ram_og.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_ram_og.v
add_fileset_file axil_reg_if.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if.v
add_fileset_file axil_reg_if_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if_rd.v
add_fileset_file axil_reg_if_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if_wr.v
add_fileset_file axil_register.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register.v
add_fileset_file axil_register_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register_rd.v
add_fileset_file axil_register_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register_wr.v
add_fileset_file priority_encoder.v VERILOG PATH ../../rtl/verilog-axi/rtl/priority_encoder.v
add_fileset_file mem_defines.sv SYSTEM_VERILOG PATH ../../rtl/mem/mem_defines.sv
add_fileset_file defines.sv SYSTEM_VERILOG PATH ../../rtl/defines.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 16
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 16
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter ID_WIDTH INTEGER 8
set_parameter_property ID_WIDTH DEFAULT_VALUE 8
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter PIPELINE_OUTPUT INTEGER 0
set_parameter_property PIPELINE_OUTPUT DEFAULT_VALUE 0
set_parameter_property PIPELINE_OUTPUT DISPLAY_NAME PIPELINE_OUTPUT
set_parameter_property PIPELINE_OUTPUT TYPE INTEGER
set_parameter_property PIPELINE_OUTPUT UNITS None
set_parameter_property PIPELINE_OUTPUT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIPELINE_OUTPUT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock clock
set_interface_property altera_axi4_slave associatedReset reset_sink
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave s_axi_araddr araddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_arburst arburst Input 2
add_interface_port altera_axi4_slave s_axi_arcache arcache Input 4
add_interface_port altera_axi4_slave s_axi_arid arid Input "((ID_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_arlen arlen Input 8
add_interface_port altera_axi4_slave s_axi_arlock arlock Input 1
add_interface_port altera_axi4_slave s_axi_arprot arprot Input 3
add_interface_port altera_axi4_slave s_axi_arready arready Output 1
add_interface_port altera_axi4_slave s_axi_arsize arsize Input 3
add_interface_port altera_axi4_slave s_axi_arvalid arvalid Input 1
add_interface_port altera_axi4_slave s_axi_awaddr awaddr Input "((ADDR_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_awburst awburst Input 2
add_interface_port altera_axi4_slave s_axi_awcache awcache Input 4
add_interface_port altera_axi4_slave s_axi_awid awid Input "((ID_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_awlen awlen Input 8
add_interface_port altera_axi4_slave s_axi_awlock awlock Input 1
add_interface_port altera_axi4_slave s_axi_awprot awprot Input 3
add_interface_port altera_axi4_slave s_axi_awready awready Output 1
add_interface_port altera_axi4_slave s_axi_awsize awsize Input 3
add_interface_port altera_axi4_slave s_axi_awvalid awvalid Input 1
add_interface_port altera_axi4_slave s_axi_bid bid Output "((ID_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_bready bready Input 1
add_interface_port altera_axi4_slave s_axi_bresp bresp Output 2
add_interface_port altera_axi4_slave s_axi_bvalid bvalid Output 1
add_interface_port altera_axi4_slave s_axi_rdata rdata Output "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_rid rid Output "((ID_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_rlast rlast Output 1
add_interface_port altera_axi4_slave s_axi_rready rready Input 1
add_interface_port altera_axi4_slave s_axi_rresp rresp Output 2
add_interface_port altera_axi4_slave s_axi_rvalid rvalid Output 1
add_interface_port altera_axi4_slave s_axi_wdata wdata Input "((DATA_WIDTH-1)) - (0) + 1"
add_interface_port altera_axi4_slave s_axi_wlast wlast Input 1
add_interface_port altera_axi4_slave s_axi_wready wready Output 1
add_interface_port altera_axi4_slave s_axi_wstrb wstrb Input 4
add_interface_port altera_axi4_slave s_axi_wvalid wvalid Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1

