# TCL File Generated by Component Editor 21.1
# Sun Mar 27 00:06:54 EDT 2022
# DO NOT MODIFY


# 
# riscy_core "riscy_core" v1.0
#  2022.03.27.00:06:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module riscy_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME riscy_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME riscy_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL riscy_core_qsys
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file proc_axi.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/proc_axi.sv
add_fileset_file dffe_wrap.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/base/dffe_wrap.sv
add_fileset_file dffe_wrap_unsyn.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/base/dffe_wrap_unsyn.sv
add_fileset_file dff_wrap.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/base/dff_wrap.sv
add_fileset_file fifo.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/base/fifo.sv
add_fileset_file iobuf.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/base/iobuf.v
add_fileset_file decode.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/decode.sv
add_fileset_file extend.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/extend.sv
add_fileset_file pc_adder.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/pc_adder.sv
add_fileset_file reg_bypass.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/reg_bypass.sv
add_fileset_file reg_ctrl.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/reg_ctrl.sv
add_fileset_file registers.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/decode/registers.sv
add_fileset_file alu.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/execute/alu.sv
add_fileset_file alu_defines.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/execute/alu_defines.sv
add_fileset_file ex_mux.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/execute/ex_mux.sv
add_fileset_file execute.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/execute/execute.sv
add_fileset_file branch_predict.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/fetch/branch_predict.sv
add_fileset_file fetch_axil.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/fetch/fetch_axil.sv
add_fileset_file pc.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/fetch/pc.sv
add_fileset_file axi_crossbar_2x1.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_crossbar_2x1.sv
add_fileset_file axi_crossbar_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_crossbar_2x1_wrapper.sv
add_fileset_file axi_defines.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_defines.sv
add_fileset_file axi_interconnect_2x1.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_interconnect_2x1.sv
add_fileset_file axi_interconnect_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_interconnect_2x1_wrapper.sv
add_fileset_file axi_interface.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_interface.sv
add_fileset_file axi_lite_interface.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axi_lite_interface.sv
add_fileset_file axil_axi_adapter.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axil_axi_adapter.sv
add_fileset_file axil_crossbar_2x1.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axil_crossbar_2x1.sv
add_fileset_file axil_crossbar_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/axil_crossbar_2x1_wrapper.sv
add_fileset_file sdram_interface.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/interconnect/sdram_interface.sv
add_fileset_file cache.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/cache.sv
add_fileset_file exclusive_monitor.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/exclusive_monitor.sv
add_fileset_file mem_defines.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/mem_defines.sv
add_fileset_file mem_sys.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/mem_sys.sv
add_fileset_file mem_sys_axil.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/mem_sys_axil.sv
add_fileset_file mem_sys_axil_wrapper.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/mem_sys_axil_wrapper.sv
add_fileset_file memory.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/mem/memory.sv
add_fileset_file ex_mem_reg.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/reg/ex_mem_reg.sv
add_fileset_file id_ex_reg.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/reg/id_ex_reg.sv
add_fileset_file if_id_reg.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/reg/if_id_reg.sv
add_fileset_file mem_wb_reg.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/reg/mem_wb_reg.sv
add_fileset_file arbiter.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/arbiter.v
add_fileset_file axi_adapter.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_adapter.v
add_fileset_file axi_adapter_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_adapter_rd.v
add_fileset_file axi_adapter_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_adapter_wr.v
add_fileset_file axi_axil_adapter.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_axil_adapter.v
add_fileset_file axi_axil_adapter_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_axil_adapter_rd.v
add_fileset_file axi_axil_adapter_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_axil_adapter_wr.v
add_fileset_file axi_cdma.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_cdma.v
add_fileset_file axi_cdma_desc_mux.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_cdma_desc_mux.v
add_fileset_file axi_crossbar.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_crossbar.v
add_fileset_file axi_crossbar_addr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_crossbar_addr.v
add_fileset_file axi_crossbar_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_crossbar_rd.v
add_fileset_file axi_crossbar_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_crossbar_wr.v
add_fileset_file axi_dma.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_dma.v
add_fileset_file axi_dma_desc_mux.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_dma_desc_mux.v
add_fileset_file axi_dma_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_dma_rd.v
add_fileset_file axi_dma_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_dma_wr.v
add_fileset_file axi_dp_ram.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_dp_ram.v
add_fileset_file axi_fifo.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_fifo.v
add_fileset_file axi_fifo_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_fifo_rd.v
add_fileset_file axi_fifo_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_fifo_wr.v
add_fileset_file axi_interconnect.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_interconnect.v
add_fileset_file axi_interconnect_wrap.py OTHER PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_interconnect_wrap.py
add_fileset_file axi_register.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_register.v
add_fileset_file axi_register_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_register_rd.v
add_fileset_file axi_register_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axi_register_wr.v
add_fileset_file axil_adapter.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_adapter.v
add_fileset_file axil_adapter_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_adapter_rd.v
add_fileset_file axil_adapter_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_adapter_wr.v
add_fileset_file axil_cdc.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_cdc.v
add_fileset_file axil_cdc_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_cdc_rd.v
add_fileset_file axil_cdc_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_cdc_wr.v
add_fileset_file axil_crossbar.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_crossbar.v
add_fileset_file axil_crossbar_addr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_crossbar_addr.v
add_fileset_file axil_crossbar_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_crossbar_rd.v
add_fileset_file axil_crossbar_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_crossbar_wr.v
add_fileset_file axil_dp_ram.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_dp_ram.v
add_fileset_file axil_interconnect.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_interconnect.v
add_fileset_file axil_reg_if.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_reg_if.v
add_fileset_file axil_reg_if_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_reg_if_rd.v
add_fileset_file axil_reg_if_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_reg_if_wr.v
add_fileset_file axil_register.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_register.v
add_fileset_file axil_register_rd.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_register_rd.v
add_fileset_file axil_register_wr.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/axil_register_wr.v
add_fileset_file priority_encoder.v VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/verilog-axi/rtl/priority_encoder.v
add_fileset_file wb.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/wb/wb.sv
add_fileset_file defines.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/defines.sv
add_fileset_file hazard_ctrl.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/hazard_ctrl.sv
add_fileset_file pref.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/pref.sv
add_fileset_file pref_defines.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/pref_defines.sv
add_fileset_file proc_axil.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/proc_axil.sv
add_fileset_file riscy_core_qsys.sv SYSTEM_VERILOG PATH ../../../GoogleDrive/Projects/riscy/rtl/riscy_core_qsys.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point altera_axi_master_1
# 
add_interface altera_axi_master_1 axi start
set_interface_property altera_axi_master_1 associatedClock clk
set_interface_property altera_axi_master_1 associatedReset reset_sink
set_interface_property altera_axi_master_1 readIssuingCapability 1
set_interface_property altera_axi_master_1 writeIssuingCapability 1
set_interface_property altera_axi_master_1 combinedIssuingCapability 1
set_interface_property altera_axi_master_1 ENABLED true
set_interface_property altera_axi_master_1 EXPORT_OF ""
set_interface_property altera_axi_master_1 PORT_NAME_MAP ""
set_interface_property altera_axi_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_master_1 SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_master_1 araddr araddr Output 32
add_interface_port altera_axi_master_1 arburst arburst Output 2
add_interface_port altera_axi_master_1 arcache arcache Output 4
add_interface_port altera_axi_master_1 arid arid Output 8
add_interface_port altera_axi_master_1 arlen arlen Output 4
add_interface_port altera_axi_master_1 arlock arlock Output 2
add_interface_port altera_axi_master_1 arprot arprot Output 3
add_interface_port altera_axi_master_1 arready arready Input 1
add_interface_port altera_axi_master_1 arsize arsize Output 3
add_interface_port altera_axi_master_1 aruser aruser Output 1
add_interface_port altera_axi_master_1 arvalid arvalid Output 1
add_interface_port altera_axi_master_1 awaddr awaddr Output 32
add_interface_port altera_axi_master_1 awburst awburst Output 2
add_interface_port altera_axi_master_1 awcache awcache Output 4
add_interface_port altera_axi_master_1 awid awid Output 8
add_interface_port altera_axi_master_1 awlen awlen Output 4
add_interface_port altera_axi_master_1 awlock awlock Output 2
add_interface_port altera_axi_master_1 awprot awprot Output 3
add_interface_port altera_axi_master_1 awready awready Input 1
add_interface_port altera_axi_master_1 awsize awsize Output 3
add_interface_port altera_axi_master_1 awuser awuser Output 1
add_interface_port altera_axi_master_1 awvalid awvalid Output 1
add_interface_port altera_axi_master_1 bid bid Input 8
add_interface_port altera_axi_master_1 bready bready Output 1
add_interface_port altera_axi_master_1 bresp bresp Input 2
add_interface_port altera_axi_master_1 bvalid bvalid Input 1
add_interface_port altera_axi_master_1 rdata rdata Input 32
add_interface_port altera_axi_master_1 rid rid Input 8
add_interface_port altera_axi_master_1 rlast rlast Input 1
add_interface_port altera_axi_master_1 rready rready Output 1
add_interface_port altera_axi_master_1 rresp rresp Input 2
add_interface_port altera_axi_master_1 rvalid rvalid Input 1
add_interface_port altera_axi_master_1 wdata wdata Output 32
add_interface_port altera_axi_master_1 wlast wlast Output 1
add_interface_port altera_axi_master_1 wready wready Input 1
add_interface_port altera_axi_master_1 wstrb wstrb Output 4
add_interface_port altera_axi_master_1 wvalid wvalid Output 1
add_interface_port altera_axi_master_1 wid wid Output 8


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clk
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1

