# TCL File Generated by Component Editor 21.1
# Sun Mar 27 02:01:28 EDT 2022
# DO NOT MODIFY


# 
# riscy_core "riscy_core" v1.0
#  2022.03.27.02:01:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module riscy_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME riscy_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME riscy_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL riscy_core_qsys
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file defines.sv SYSTEM_VERILOG PATH ../../rtl/defines.sv IS_CONFIGURATION_PACKAGE
add_fileset_file hazard_ctrl.sv SYSTEM_VERILOG PATH ../../rtl/hazard_ctrl.sv
add_fileset_file pref.sv SYSTEM_VERILOG PATH ../../rtl/pref.sv
add_fileset_file pref_defines.sv SYSTEM_VERILOG PATH ../../rtl/pref_defines.sv
add_fileset_file proc.sv SYSTEM_VERILOG PATH ../../rtl/proc.sv
add_fileset_file proc_axi.sv SYSTEM_VERILOG PATH ../../rtl/proc_axi.sv
add_fileset_file proc_axil.sv SYSTEM_VERILOG PATH ../../rtl/proc_axil.sv
add_fileset_file dff_wrap.sv SYSTEM_VERILOG PATH ../../rtl/base/dff_wrap.sv
add_fileset_file dffe_wrap.sv SYSTEM_VERILOG PATH ../../rtl/base/dffe_wrap.sv
add_fileset_file dffe_wrap_unsyn.sv SYSTEM_VERILOG PATH ../../rtl/base/dffe_wrap_unsyn.sv
add_fileset_file fifo.sv SYSTEM_VERILOG PATH ../../rtl/base/fifo.sv
add_fileset_file iobuf.v VERILOG PATH ../../rtl/base/iobuf.v
add_fileset_file rom.sv SYSTEM_VERILOG PATH ../../rtl/base/rom.sv
add_fileset_file decode.sv SYSTEM_VERILOG PATH ../../rtl/decode/decode.sv
add_fileset_file extend.sv SYSTEM_VERILOG PATH ../../rtl/decode/extend.sv
add_fileset_file pc_adder.sv SYSTEM_VERILOG PATH ../../rtl/decode/pc_adder.sv
add_fileset_file reg_bypass.sv SYSTEM_VERILOG PATH ../../rtl/decode/reg_bypass.sv
add_fileset_file reg_ctrl.sv SYSTEM_VERILOG PATH ../../rtl/decode/reg_ctrl.sv
add_fileset_file registers.sv SYSTEM_VERILOG PATH ../../rtl/decode/registers.sv
add_fileset_file alu.sv SYSTEM_VERILOG PATH ../../rtl/execute/alu.sv
add_fileset_file alu_defines.sv SYSTEM_VERILOG PATH ../../rtl/execute/alu_defines.sv
add_fileset_file ex_mux.sv SYSTEM_VERILOG PATH ../../rtl/execute/ex_mux.sv
add_fileset_file execute.sv SYSTEM_VERILOG PATH ../../rtl/execute/execute.sv
add_fileset_file branch_predict.sv SYSTEM_VERILOG PATH ../../rtl/fetch/branch_predict.sv
add_fileset_file fetch.sv SYSTEM_VERILOG PATH ../../rtl/fetch/fetch.sv
add_fileset_file fetch_axil.sv SYSTEM_VERILOG PATH ../../rtl/fetch/fetch_axil.sv
add_fileset_file fetch_axil_tb.sv SYSTEM_VERILOG PATH ../../rtl/fetch/fetch_axil_tb.sv
add_fileset_file instr_mem.sv SYSTEM_VERILOG PATH ../../rtl/fetch/instr_mem.sv
add_fileset_file pc.sv SYSTEM_VERILOG PATH ../../rtl/fetch/pc.sv
add_fileset_file axi_crossbar_2x1.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_crossbar_2x1.sv
add_fileset_file axi_crossbar_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_crossbar_2x1_wrapper.sv
add_fileset_file axi_defines.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_defines.sv
add_fileset_file axi_interconnect_2x1.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_interconnect_2x1.sv
add_fileset_file axi_interconnect_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_interconnect_2x1_wrapper.sv
add_fileset_file axi_interface.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_interface.sv
add_fileset_file axi_lite_interface.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_lite_interface.sv
add_fileset_file axi_ram_sv_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axi_ram_sv_wrapper.sv
add_fileset_file axil_axi_adapter.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axil_axi_adapter.sv
add_fileset_file axil_crossbar_2x1.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axil_crossbar_2x1.sv
add_fileset_file axil_crossbar_2x1_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axil_crossbar_2x1_wrapper.sv
add_fileset_file axil_ram_sv_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/axil_ram_sv_wrapper.sv
add_fileset_file sdram_interface.sv SYSTEM_VERILOG PATH ../../rtl/interconnect/sdram_interface.sv
add_fileset_file cache.sv SYSTEM_VERILOG PATH ../../rtl/mem/cache.sv
add_fileset_file exclusive_monitor.sv SYSTEM_VERILOG PATH ../../rtl/mem/exclusive_monitor.sv
add_fileset_file mem_defines.sv SYSTEM_VERILOG PATH ../../rtl/mem/mem_defines.sv
add_fileset_file mem_sys.sv SYSTEM_VERILOG PATH ../../rtl/mem/mem_sys.sv
add_fileset_file mem_sys_axil.sv SYSTEM_VERILOG PATH ../../rtl/mem/mem_sys_axil.sv
add_fileset_file mem_sys_axil_wrapper.sv SYSTEM_VERILOG PATH ../../rtl/mem/mem_sys_axil_wrapper.sv
add_fileset_file memory.sv SYSTEM_VERILOG PATH ../../rtl/mem/memory.sv
add_fileset_file ex_mem_reg.sv SYSTEM_VERILOG PATH ../../rtl/reg/ex_mem_reg.sv
add_fileset_file id_ex_reg.sv SYSTEM_VERILOG PATH ../../rtl/reg/id_ex_reg.sv
add_fileset_file if_id_reg.sv SYSTEM_VERILOG PATH ../../rtl/reg/if_id_reg.sv
add_fileset_file mem_wb_reg.sv SYSTEM_VERILOG PATH ../../rtl/reg/mem_wb_reg.sv
add_fileset_file arbiter.v VERILOG PATH ../../rtl/verilog-axi/rtl/arbiter.v
add_fileset_file axi_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter.v
add_fileset_file axi_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter_rd.v
add_fileset_file axi_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_adapter_wr.v
add_fileset_file axi_axil_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter.v
add_fileset_file axi_axil_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter_rd.v
add_fileset_file axi_axil_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_axil_adapter_wr.v
add_fileset_file axi_cdma.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_cdma.v
add_fileset_file axi_cdma_desc_mux.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_cdma_desc_mux.v
add_fileset_file axi_crossbar.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar.v
add_fileset_file axi_crossbar_addr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_addr.v
add_fileset_file axi_crossbar_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_rd.v
add_fileset_file axi_crossbar_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_crossbar_wr.v
add_fileset_file axi_dma.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma.v
add_fileset_file axi_dma_desc_mux.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_desc_mux.v
add_fileset_file axi_dma_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_rd.v
add_fileset_file axi_dma_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dma_wr.v
add_fileset_file axi_dp_ram.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_dp_ram.v
add_fileset_file axi_fifo.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo.v
add_fileset_file axi_fifo_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo_rd.v
add_fileset_file axi_fifo_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_fifo_wr.v
add_fileset_file axi_interconnect.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_interconnect.v
add_fileset_file axi_register.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register.v
add_fileset_file axi_register_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register_rd.v
add_fileset_file axi_register_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axi_register_wr.v
add_fileset_file axil_adapter.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter.v
add_fileset_file axil_adapter_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter_rd.v
add_fileset_file axil_adapter_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_adapter_wr.v
add_fileset_file axil_cdc.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc.v
add_fileset_file axil_cdc_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc_rd.v
add_fileset_file axil_cdc_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_cdc_wr.v
add_fileset_file axil_crossbar.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar.v
add_fileset_file axil_crossbar_addr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_addr.v
add_fileset_file axil_crossbar_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_rd.v
add_fileset_file axil_crossbar_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_crossbar_wr.v
add_fileset_file axil_dp_ram.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_dp_ram.v
add_fileset_file axil_interconnect.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_interconnect.v
add_fileset_file axil_reg_if.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if.v
add_fileset_file axil_reg_if_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if_rd.v
add_fileset_file axil_reg_if_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_reg_if_wr.v
add_fileset_file axil_register.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register.v
add_fileset_file axil_register_rd.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register_rd.v
add_fileset_file axil_register_wr.v VERILOG PATH ../../rtl/verilog-axi/rtl/axil_register_wr.v
add_fileset_file priority_encoder.v VERILOG PATH ../../rtl/verilog-axi/rtl/priority_encoder.v
add_fileset_file wb.sv SYSTEM_VERILOG PATH ../../rtl/wb/wb.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 rst beginbursttransfer Input 1
add_interface_port avalon_slave_0 awid readdata Output 8
add_interface_port avalon_slave_0 wid readdata Output 8
add_interface_port avalon_slave_0 awaddr readdata Output 32
add_interface_port avalon_slave_0 awlen readdata Output 4
add_interface_port avalon_slave_0 awsize readdata Output 3
add_interface_port avalon_slave_0 awburst readdata Output 2
add_interface_port avalon_slave_0 awlock readdata Output 2
add_interface_port avalon_slave_0 awcache readdata Output 4
add_interface_port avalon_slave_0 awprot readdata Output 3
add_interface_port avalon_slave_0 awuser writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 awvalid writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 awready beginbursttransfer Input 1
add_interface_port avalon_slave_0 wdata readdata Output 32
add_interface_port avalon_slave_0 wstrb readdata Output 4
add_interface_port avalon_slave_0 wlast writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 wvalid writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 wready beginbursttransfer Input 1
add_interface_port avalon_slave_0 bid writebyteenable_n Input 8
add_interface_port avalon_slave_0 bresp writebyteenable_n Input 2
add_interface_port avalon_slave_0 bvalid beginbursttransfer Input 1
add_interface_port avalon_slave_0 bready writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 arid readdata Output 8
add_interface_port avalon_slave_0 araddr readdata Output 32
add_interface_port avalon_slave_0 arlen readdata Output 4
add_interface_port avalon_slave_0 arsize readdata Output 3
add_interface_port avalon_slave_0 arburst readdata Output 2
add_interface_port avalon_slave_0 arlock readdata Output 2
add_interface_port avalon_slave_0 arcache readdata Output 4
add_interface_port avalon_slave_0 arprot readdata Output 3
add_interface_port avalon_slave_0 aruser writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 arvalid writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 arready beginbursttransfer Input 1
add_interface_port avalon_slave_0 rid writebyteenable_n Input 8
add_interface_port avalon_slave_0 rdata writebyteenable_n Input 32
add_interface_port avalon_slave_0 rresp writebyteenable_n Input 2
add_interface_port avalon_slave_0 rlast beginbursttransfer Input 1
add_interface_port avalon_slave_0 rvalid beginbursttransfer Input 1
add_interface_port avalon_slave_0 rready writeresponsevalid_n Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

